# Uncomment the next line to define a global platform for your project
platform :ios, ‘9.0’
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'DYZB' do

pod 'Alamofire', '~> 4.4.0'
pod 'Kingfisher', '~> 3.1.4'

end
